AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  will-it-crash-functions

Globals:
  Function:
    Environment:
      Variables:
        GUESSES_TABLE_NAME: !Ref Guesses
        BTCPRICES_TABLE_NAME: !Ref BtcPrices

Resources:
  CheckGuessService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: src/index.checkGuessServiceHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BtcPrices
      Events:
        Guess:
          Type: Api
          Properties:
            Path: /guess
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  LoadPlayerService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: src/index.loadPlayerServiceHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Guesses
        - DynamoDBCrudPolicy:
            TableName: !Ref BtcPrices
      Events:
        LoadPlayer:
          Type: Api
          Properties:
            Path: /load-player
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts

  Guesses:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: playerId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
  BtcPrices:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: price
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: price
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
Outputs:
  CheckGuessServiceApi:
    Description: "API Gateway endpoint URL for CheckGuessService"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/guess/"
  CheckGuessService:
    Description: "CheckGuessService Lambda Function ARN"
    Value: !GetAtt CheckGuessService.Arn
  CheckGuessServiceIamRole:
    Description: "Implicit IAM Role created for CheckGuessService"
    Value: !GetAtt CheckGuessServiceRole.Arn
  LoadPlayerServiceApi:
    Description: "API Gateway endpoint URL for LoadPlayerService"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/load-player/"
  LoadPlayerService:
    Description: "LoadPlayerService Lambda Function ARN"
    Value: !GetAtt LoadPlayerService.Arn
  LoadPlayerServiceIamRole:
    Description: "Implicit IAM Role created for LoadPlayerService"
    Value: !GetAtt LoadPlayerServiceRole.Arn
