AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  will-it-crash-functions

Resources:
  CheckGuessService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: src/index.checkGuessServiceHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Guesses
        - DynamoDBCrudPolicy:
            TableName: !Ref BtcPrices
      Events:
        Guess:
          Type: Api
          Properties:
            Path: /guess
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts

  Guesses:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: guesses
      KeySchema:
        - AttributeName: playerId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
  BtcPrices:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: btcPrices
      KeySchema:
        - AttributeName: price
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: price
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
Outputs:
  CheckGuessServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for CheckGuessService"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/guess/"
  CheckGuessService:
    Description: "CheckGuessService Lambda Function ARN"
    Value: !GetAtt CheckGuessService.Arn
  CheckGuessServiceIamRole:
    Description: "Implicit IAM Role created for CheckGuessService"
    Value: !GetAtt CheckGuessServiceRole.Arn
